CREATE TABLE IF NOT EXISTS verification
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_verification_code VARCHAR(100),
    phone_verification_code VARCHAR(10),
    is_email_verified       BOOLEAN DEFAULT FALSE,
    is_phone_verified       BOOLEAN DEFAULT FALSE,
    reset_code              VARCHAR(100),
    created_at              TIMESTAMP DEFAULT NOW(),
    updated_at              TIMESTAMP DEFAULT NOW()
    );

CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(150),
    phone_number    VARCHAR(15),
    password        TEXT,
    role            VARCHAR(15),
    verification_id BIGINT,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_users_verification FOREIGN KEY (verification_id) REFERENCES verification (id)
    );