spring.application.name=quickstart
# Auth Starter Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/quickstart
spring.datasource.username=postgres
spring.datasource.password=devpassword

ctlabs.auth.jwt.secret-key=${JWK_SECRET_KEY:6c6f6e675f616e645f7365637572655f7365637265745f6b6579}
# Exclude default Spring Security config for compatibility
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration
